### ISSUE TITLE
Performance issues with VLP32C LiDAR in beach-like environment

### ISSUE THREAD

**Issue by spirit-man** [kevin2431/Traj-LO#16]
Thanks for your remarkable work. I've successfully tested Traj-LO with the KITTI dataset, but I'm encountering significant accuracy issues when using it with a Velodyne VLP32C LiDAR in a beach-like environment. Interestingly, A-LOAM performs better in the same scenario, which suggests there might be some specific configurations needed for my setup.

I've tried the following parameter sets:

```yaml
# Set 1
trajectory:
  init_interval: 2e8
  seg_interval: 4e7
  seg_num: 5
  kinematic_constrain: 0.2
  init_pose_weight: 1e9
  converge_thresh: 0.001
  max_iterations: 25

mapping:
  ds_size: 0.4
  voxel_size: 0.4
  max_voxel_num: 20
  planer_thresh: 0.1
  max_range: 120
  min_range: 1

# Set 2 (only different in kinematic_constrain)
trajectory:
  kinematic_constrain: 2.0
  # other parameters remain the same

# Set 3 (only different in kinematic_constrain)
trajectory:
  kinematic_constrain: 4.0
  # other parameters remain the same
```

Results for set1 is as following:

<img width="1044" alt="Image" src="https://github.com/user-attachments/assets/fe0a3213-0c8b-4c9f-8116-188187b1f10b" />

In all test cases, the estimated trajectory tends to exhibit spiral-shaped loops.

Could you please provide some guidance on:

1. Potential reasons for the performance difference between KITTI and VLP32C scenarios
2. Recommended parameter adjustments for beach-like environments
3. Any additional considerations for VLP32C integration

Thank you for your help!
